import Head from "next/head";
import About from "../components/home/about/About";
import Banner from "../components/home/banner/Banner";
import Contact from "../components/home/contact/Contact";
import Services from "../components/home/services/Service";
import WhyUS from "../components/home/whyus/WhyUs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>HDF - Habitat de France</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner/>
        <Services/>
        <WhyUS/>
        <About/>
        <Contact/>
      </main>
    </div>
  );
}
